CREATE DATABASE QLQTS
GO

USE QLQTS
GO

create table LOAISP
(
	IdLoaiSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaLoaiSP NVARCHAR(20) UNIQUE NOT NULL,
	TenLoaiSP NVARCHAR(50) NOT NULL,
	TrangThai INT NOT NULL
)
GO

CREATE TABLE SIZE
(
	IdSize UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaSize NVARCHAR(20) UNIQUE NOT NULL,
	TenSize NVARCHAR(50) NOT NULL,
	Gia DECIMAL(20,0) NOT NULL, 
	TrangThai INT NOT NULL
)
GO

CREATE TABLE TOPPING
(
	IdTopping UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaTopping NVARCHAR(20) UNIQUE NOT NULL,
	TenTopping NVARCHAR(50) NOT NULL,
	Gia DECIMAL(20,0) NOT NULL,
	TrangThai INT NOT NULL
)
GO

CREATE TABLE KHUYENMAI
(
	IdKM UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKM NVARCHAR(20) UNIQUE NOT NULL,
	TenKM NVARCHAR(50) NOT NULL,
	NgayBatDau DATE NOT NULL,
	NgayKetThuc DATE NOT NULL,
	HinhThucKM NVARCHAR(30) NOT NULL,
	GiaTri INT NOT NULL,
	TrangThai INT NOT NULL
)
GO

CREATE TABLE COMBO
(
	IdCombo UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaCombo NVARCHAR(20) UNIQUE NOT NULL,
	TenCombo NVARCHAR(60) NOT NULL,
	GiaCombo DECIMAL(20,0) NOT NULL,
	SoLuong INT NOT NULL,
	NgayTao DATE NOT NULL,
	GhiChu NVARCHAR(100) NOT NULL,
	TrangThai INT NOT NULL
)
GO

CREATE TABLE SANPHAM
(
	IdSanPham UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaSP NVARCHAR(20) UNIQUE NOT NULL,
	TenSP NVARCHAR(100) NOT NULL,
	DonGia DECIMAL(20,0) NOT NULL,
	HinhAnh NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(100) NOT NULL,
	TrangThai INT NOT NULL,
	IdLoaiSP UNIQUEIDENTIFIER NOT NULL,
	IdSize UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE NHANVIEN
(
	IdNhanVien UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaNV NVARCHAR(20) UNIQUE NOT NULL,
	HoTenNV NVARCHAR(50) NOT NULL,
	SoDT NVARCHAR(10) NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	NgaySinh DATE NOT NULL,
	Email NVARCHAR(30) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	ChucVu NVARCHAR(50) NOT NULL,
	MatKhau NVARCHAR(20) NOT NULL,
	TrangThai BIT NOT NULL,
	IdChucVu UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE KHACHHANG
(
	IdKhachHang UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKH NVARCHAR(20) UNIQUE NOT NULL,
	HoTenKH NVARCHAR(50) NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	NgaySinh DATE NOT NULL,
	SoDT NVARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	GhiChu NVARCHAR(100) NOT NULL,
	TrangThai INT NOT NULL
)
GO

CREATE TABLE HOADON
(
	IdHoaDon UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaHD NVARCHAR(20) UNIQUE NOT NULL,
	NgayTao DATE NOT NULL,
	TongTien DECIMAL(20,0) NOT NULL,
	TienApDungKM DECIMAL(20,0) NOT NULL,
	TienKHThanhToan DECIMAL(20,0) NOT NULL,
	NgayThanhToan DATE NOT NULL,
	GhiChu VARCHAR(200) NOT NULL,
	TrangThai INT NOT NULL,
	IdNhanVien UNIQUEIDENTIFIER NOT NULL,
	IdKhachHang UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE HOADONCHITIET
(
	IdHoaDonCT UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	DonGia DECIMAL(20,0) NOT NULL,
	SoLuong INT NOT NULL,
	GiaTopping DECIMAL(20,0) NOT NULL,
	TrangThai VARCHAR(50) NOT NULL,
	IdHoaDon UNIQUEIDENTIFIER NOT NULL,
	IdSanPham UNIQUEIDENTIFIER NOT NULL,
	IdKM UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE GIAOCA
(
	IdGiaoCa UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaCa VARCHAR(20) NOT NULL,
	ThoiDiemBatDau DATE NOT NULL,
	ThoiDiemKetThuc DATE NOT NULL,
	SoTienBanDau DECIMAL(20,0) NOT NULL,
	TienDoanhThu DECIMAL(20,0) NOT NULL,
	TienPhatSinh DECIMAL(20,0) NOT NULL,
	TienHienCo DECIMAL(20,0) NOT NULL,
	GhiChu VARCHAR(50) NOT NULL,
	IdNhanVien UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE HDCT_TOPPING
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdHoaDonCT UNIQUEIDENTIFIER,
	IdTopping UNIQUEIDENTIFIER,
	TrangThai INT NOT NULL
)
GO

CREATE TABLE COMBO_SANPHAM
(
	IdComboSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdSanPham UNIQUEIDENTIFIER,
	IdCombo UNIQUEIDENTIFIER,
	TrangThai INT NOT NULL
)
GO

--Tạo quan hệ giữa các bảng
-- Sản phẩm - Loại SP
ALTER TABLE SANPHAM ADD FOREIGN KEY (IdLoaiSP) REFERENCES LOAISP(IdLoaiSP)
-- Sản phẩm - Size
ALTER TABLE SANPHAM ADD FOREIGN KEY (IdSize) REFERENCES SIZE(IdSize)
-- Hóa đơn - nhân viên
ALTER TABLE HOADON ADD FOREIGN KEY (IdNhanVien) REFERENCES NHANVIEN(IdNhanVien)
-- Hóa đơn - khách hàng
ALTER TABLE HOADON ADD FOREIGN KEY (IdKhachHang) REFERENCES KHACHHANG(IdKhachHang)
-- Hóa đơn chi tiết - 