/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GiaoCa;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.GiaoCa_service;
import service.nhanvien_service;
import serviceimql.GiaoCa_serviceimpl;
import serviceimql.Nhanvien_serviceimpl;
import viewModel.GiaoCaViewModel2;

/**
 *
 * @author kn134
 */
public class ViewGiaoCaQuanLy extends javax.swing.JFrame {

    List<GiaoCa> listgc = new ArrayList<>();
    DefaultTableModel model;
    private final String mac;
    private GiaoCa_service giaoca = new GiaoCa_serviceimpl();
    private nhanvien_service nhanvien = new Nhanvien_serviceimpl();
    private double tcl = tienconlai1;
    private double tlr = tienlayra1;
    static double tienconlai1;
    static double tienlayra1;

    /**
     * Creates new form ViewGiaoCaQuanLy
     */
    public ViewGiaoCaQuanLy(String mac) {
        initComponents();
        this.mac = mac;
        setLocationRelativeTo(null);
        if (txtsotienbandau.getText().equals("")) {
            txtsotienbandau.setText("0");
        }
        if (txttongtiencahienco.getText().equals("")) {
            txttongtiencahienco.setText("0");
        }
        if (txttiendoanhthu.getText().equals("")) {
            txttiendoanhthu.setText("0");
        }
        if (txttienchuthu.getText().equals("")) {
            txttienchuthu.setText("0");
        }
        if (txttienphatsinh.getText().equals("")) {
            txttienphatsinh.setText("0");
        }
        loadTien();
        txtmaca.setText(mac);
        txtsotienbandau.setText(giaoca.getGiaoCaByMa(mac).getTienbandau() + "");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        txtthoidiembatdau.setText(sdf.format(giaoca.getGiaoCaByMa(mac).getThoigianbatdau()));
        Date dt = giaoca.getGiaoCaByMa(mac).getThoigianbatdau();
        txttiendoanhthu.setText(giaoca.getDoanhThuByThoiGianBatDau(dt).getTiendoanhthu() + "");
        Timestamp tdkt = giaoca.getDoanhThuByThoiGianBatDau(dt).getThoidiemketthuc();
        txtthoidiemketthuc.setText(sdf.format(tdkt));
        txttongtiencahienco.setText(giaoca.getGiaoCaByMa(mac).getTienbandau() + giaoca.getDoanhThuByThoiGianBatDau(dt).getTiendoanhthu() + "");
        loadTien();
//        lblmaca.setText(giaoca.getAllGiaoCaByMaCa(mac).getMaca());
//        lblthoidiembatdau.setText(giaoca.getAllGiaoCaByMaCa(mac).getThoidiembatdau()+"");
//        lblthoidiemketthuc.setText(new Date()+"");
//        lblghichu.setText(giaoca.getAllGiaoCaByMaCa(mac).getGhichu());
//        lbltiendoanhthu.setText(giaoca.getAllGiaoCaByMaCa(mac).getTiendoanhthu()+"");
//        lblsotienbandau.setText(giaoca.getAllGiaoCaByMaCa(mac).getTienchuthu()+"");
//        lbltongtienhienco.setText(giaoca.getAllGiaoCaByMaCa(mac).getTienchuthu()+"");
//        txttienphatsinh.setText(giaoca.getAllGiaoCaByMaCa(mac).getTienphatsinh()+"");  
        fillGiaoCaToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblgiaoca = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txttu = new com.toedter.calendar.JDateChooser();
        txtden = new com.toedter.calendar.JDateChooser();
        txtmaca = new javax.swing.JLabel();
        txtthoidiembatdau = new javax.swing.JLabel();
        txtthoidiemketthuc = new javax.swing.JLabel();
        txtsotienbandau = new javax.swing.JLabel();
        txttiendoanhthu = new javax.swing.JLabel();
        txttongtiencahienco = new javax.swing.JLabel();
        txttienchuthu = new javax.swing.JLabel();
        txttienphatsinh = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtghichu = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Giao ca");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Mã ca:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Thời điểm bắt đầu :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Thời điểm kết thúc :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Tổng tiền ca hiện có ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Số tiền ban đầu");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GIAO CA");

        tblgiaoca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, "", "", "", null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ca", "Tên nhân viên", "Thời gian bắt đầu", "Số tiền ban đầu", "Tiền doanh thu", "Tổng tiền hiện có", "Tiền chủ thu", "Tiền phát sinh", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblgiaoca);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("Tiền chủ thu");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("Tiền doanh thu");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("Tiền phát sinh :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("Ghi chú");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel29.setText("Từ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel30.setText("đến");

        jButton4.setText("Xuất File");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txttienphatsinh.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txttienphatsinhCaretUpdate(evt);
            }
        });

        txtghichu.setColumns(20);
        txtghichu.setRows(5);
        txtghichu.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtghichuCaretUpdate(evt);
            }
        });
        jScrollPane3.setViewportView(txtghichu);

        jButton2.setText("Xác nhận");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset ca");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        jButton5.setText("Lọc");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtmaca, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtthoidiembatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtthoidiemketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jScrollPane3)))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtden, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txttu, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(1035, 1035, 1035))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttienphatsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttienchuthu)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsotienbandau)
                                            .addComponent(txttiendoanhthu)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttongtiencahienco)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel16, jLabel19, jLabel2, jLabel3, jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel17, jLabel18, jLabel6});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtmaca, txtsotienbandau, txttienchuthu, txttiendoanhthu, txttienphatsinh, txttongtiencahienco});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtmaca)
                            .addComponent(txtsotienbandau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel17)
                            .addComponent(txttiendoanhthu)
                            .addComponent(txtthoidiembatdau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txttongtiencahienco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txttienchuthu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(txttienphatsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtthoidiemketthuc)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel16, jLabel17, jLabel18, jLabel19, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, txtmaca, txtsotienbandau, txtthoidiembatdau, txtthoidiemketthuc, txttienchuthu, txttiendoanhthu, txttienphatsinh, txttongtiencahienco});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel29, jLabel30, txtden, txttu});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GiaoCaViewModel2 gc = new GiaoCaViewModel2();
        gc.setMaca(mac);

        String dt = txtthoidiemketthuc.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            Date date1 = sdf.parse(dt);
            gc.setThoidiemketthuc(date1);
        } catch (ParseException ex) {
            Logger.getLogger(ViewGiaoCaNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

//        gc.setThoidiemketthuc(new Date());
        gc.setTiendoanhthu(Double.parseDouble(txttiendoanhthu.getText()));
        gc.setTonghienco(Double.parseDouble(txttongtiencahienco.getText()));
        gc.setTienchuthu(Double.parseDouble(txttienchuthu.getText()));
//        gc.setTienphatsinh(Double.parseDouble(txttienphatsinh.getText()));
        
        try {
            double tps = Double.parseDouble(txttienphatsinh.getText());
            if (tps < 0) {
                JOptionPane.showMessageDialog(this, "Số tiền nhập phải lớn hơn 0");
                txttienphatsinh.requestFocus();
                return;
            }
            gc.setTienphatsinh(tps);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số tiền nhập vào phải là số");
            return;
        }
        
        if (txtghichu.getText().equals("")) {
            gc.setGhichu("");
        } else {
            gc.setGhichu(txtghichu.getText());
        }
        giaoca.updateGC(gc);
        JOptionPane.showMessageDialog(this, "Giao ca thành công");
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook wordbook = new XSSFWorkbook();
            XSSFSheet sheet = wordbook.createSheet("Giao ca");
            XSSFRow row = null;
            XSSFCell cell = null;
            row = sheet.createRow(3);

            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã ca");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Tên nhân viên");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Thời điểm bắt đầu");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Số tiền ban đầu");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Tiền doanh thu");

            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Tổng tiền hiện có");

            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Tiền chủ thu");

            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Tiền phát sinh");

            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue("Ghi chú");

            for (int i = 0; i < tblgiaoca.getRowCount(); i++) {
                row = sheet.createRow(4 + i);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue((String) tblgiaoca.getValueAt(i, 0));

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue((String) tblgiaoca.getValueAt(i, 1));

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue((String) tblgiaoca.getValueAt(i, 2));

                cell = row.createCell(3, CellType.NUMERIC);
                cell.setCellValue((double) tblgiaoca.getValueAt(i, 3));

                cell = row.createCell(4, CellType.NUMERIC);
                cell.setCellValue((double) tblgiaoca.getValueAt(i, 4));

                cell = row.createCell(5, CellType.NUMERIC);
                cell.setCellValue((double) tblgiaoca.getValueAt(i, 5));

                cell = row.createCell(6, CellType.NUMERIC);
                cell.setCellValue((double) tblgiaoca.getValueAt(i, 6));

                cell = row.createCell(7, CellType.NUMERIC);
                cell.setCellValue((double) tblgiaoca.getValueAt(i, 7));

                cell = row.createCell(8, CellType.STRING);
                cell.setCellValue((String) tblgiaoca.getValueAt(i, 8));

            }
            JFileChooser j = new JFileChooser();
            j.setDialogTitle("Hãy chọn địa chỉ muốn xuất file !");
            int rs = j.showSaveDialog(null);
            String Path = j.getSelectedFile().getAbsolutePath();
            String name = j.getSelectedFile().getName();
            String exclePath = Path + ".xlsx";
            try {
                FileOutputStream fos = new FileOutputStream(exclePath);
                wordbook.write(fos);
                fos.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            Desktop.getDesktop().open(new File(exclePath));
            JOptionPane.showMessageDialog(this, "Success");
        } catch (Exception e) {
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            double tthc = Double.parseDouble(txttongtiencahienco.getText());
            ViewResetCa vrs = new ViewResetCa(tthc);
            vrs.setVisible(true);
        } catch (Exception e) {
        }
        txttienchuthu.setText(tienlayra1 + "");
        txttongtiencahienco.setText(Double.parseDouble(txttongtiencahienco.getText()) - Double.parseDouble(txttienchuthu.getText()) + "");
        loadTien();
        txtghichu.setText("Đã rút tiền khỏi ca");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttienphatsinhCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txttienphatsinhCaretUpdate
        // TODO add your handling code here:
        try {
            txttongtiencahienco.setText(Double.parseDouble(txttienphatsinh.getText()) + Double.parseDouble(txttiendoanhthu.getText()) + Double.parseDouble(txtsotienbandau.getText()) + "");
            loadTien();
        } catch (Exception e) {
        }
        loadTien();
    }//GEN-LAST:event_txttienphatsinhCaretUpdate

    private void txtghichuCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtghichuCaretUpdate
        // TODO add your handling code here:
        loadTien();
    }//GEN-LAST:event_txtghichuCaretUpdate

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (txttu.getCalendar() == null && txtden.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn giá trị để lọc");
        } else if (txtden.getCalendar() == null) {
            Date tu = txttu.getDate();
            fillToTable(tu);
//            JOptionPane.showMessageDialog(this, "Đến đang trống");
//            txtden.requestFocus();
        } else if (txttu.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thời gian bắt đầu");
            txttu.requestFocus();
            return;
        } else {
            Date tu = txttu.getDate();
            Date den = txtden.getDate();
            fillToTable(tu, den);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewGiaoCaQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewGiaoCaQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewGiaoCaQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewGiaoCaQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewGiaoCaQuanLy().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblgiaoca;
    private com.toedter.calendar.JDateChooser txtden;
    private javax.swing.JTextArea txtghichu;
    private javax.swing.JLabel txtmaca;
    private javax.swing.JLabel txtsotienbandau;
    private javax.swing.JLabel txtthoidiembatdau;
    private javax.swing.JLabel txtthoidiemketthuc;
    private javax.swing.JLabel txttienchuthu;
    private javax.swing.JLabel txttiendoanhthu;
    private javax.swing.JTextField txttienphatsinh;
    private javax.swing.JLabel txttongtiencahienco;
    private com.toedter.calendar.JDateChooser txttu;
    // End of variables declaration//GEN-END:variables

    private void fillGiaoCaToTable() {
        listgc = giaoca.getAllGiaoCa();
        model = (DefaultTableModel) tblgiaoca.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listgc.size(); i++) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String idnv = listgc.get(i).getIdnhanvien();
            String tennv = nhanvien.getNVbyid(idnv).getHotenNv();
            Object[] data = new Object[]{
                listgc.get(i).getMaca(), tennv, sdf.format(listgc.get(i).getThoidiembatdau()), listgc.get(i).getTienbandau(), listgc.get(i).getTiendoanhthu(), listgc.get(i).getTonghienco(), listgc.get(i).getTienchuthu(), listgc.get(i).getTienphatsinh(), listgc.get(i).getGhichu()
            };
            model.addRow(data);
        }
    }

    private void loadTien() {
        txttienchuthu.setText(tienlayra1 + "");
        double tienKQ = Double.parseDouble(txtsotienbandau.getText()) + Double.parseDouble(txttiendoanhthu.getText()) + Double.parseDouble(txttienphatsinh.getText()) - Double.parseDouble(txttienchuthu.getText());
        txttongtiencahienco.setText(tienKQ + "");
    }

    private void fillToTable(Date tu, Date den) {
        listgc = giaoca.getGCByTG(tu, den);
        model = (DefaultTableModel) tblgiaoca.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listgc.size(); i++) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String idnv = listgc.get(i).getIdnhanvien();
            String tennv = nhanvien.getNVbyid(idnv).getHotenNv();
            Object[] data = new Object[]{
                listgc.get(i).getMaca(), tennv, sdf.format(listgc.get(i).getThoidiembatdau()), listgc.get(i).getTienbandau(), listgc.get(i).getTiendoanhthu(), listgc.get(i).getTonghienco(), listgc.get(i).getTienchuthu(), listgc.get(i).getTienphatsinh(), listgc.get(i).getGhichu()
            };
            model.addRow(data);
        }
    }

    private void fillToTable(Date tu) {
        listgc = giaoca.getGCByTG(tu);
        model = (DefaultTableModel) tblgiaoca.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listgc.size(); i++) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String idnv = listgc.get(i).getIdnhanvien();
            String tennv = nhanvien.getNVbyid(idnv).getHotenNv();
            Object[] data = new Object[]{
                listgc.get(i).getMaca(), tennv, sdf.format(listgc.get(i).getThoidiembatdau()), listgc.get(i).getTienbandau(), listgc.get(i).getTiendoanhthu(), listgc.get(i).getTonghienco(), listgc.get(i).getTienchuthu(), listgc.get(i).getTienphatsinh(), listgc.get(i).getGhichu()
            };
            model.addRow(data);
        }
    }
}
